name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  CLIENT_APP_NAME: ${{ 'draw-pixel-art-app' }}
  SERVER_APP_NAME: ${{ 'draw-pixel-art-service' }}

jobs:
      
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v3

    # Build Docker image
    - name: Build images
      run: docker build . --file draw-pixel-art-app/Dockerfile --tag draw-pixel-art-app

    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        heroku container:push draw-pixel-art-app -a draw-pixel-art-app
        heroku container:release draw-pixel-art-app -a draw-pixel-art-app
        
